# This file is managed by 'repo_helper'. Don't edit it directly.
---

language: python
dist: xenial
cache: pip
python:
  - '3.6'
  - '3.7'
  - '3.8'
  - '3.9-dev'

install:

  - pip install pip  --upgrade
  - pip install tox tox-travis
  - pip install coveralls coverage_pyver_pragma

script:
  - tox
after_success:
  - coveralls


stages:
  - test
  - deploy_pypi



jobs:
  include:
    - stage: deploy_pypi
      python: "3.6"
      script: skip
      deploy:
        on:
          tags: true
          repo: domdfcoding/extras_require
        provider: pypi
        user: "DomDF"
        password:
          secure: X5DWz/pm6eilhrJBTDnp8Mm8S6zEBrnKb1LZq5BxtV03tZuwTTgYSqRbI0fB2LGC/jFsuI7KF4c35NJ/uGHR29taxIC7HWAYQI/ROjqDEjzFxZVbDXeDEtPYWGXDW+qwd+to4STOTkruHC9ZhUQnNqME2gWsPWFqKBKFEfg3N3MzIWifO/bUQWa49KY6u0XsiPGlWfhn4hxHA8MuUimc+ZPsK6pNseXrEYlcsTcTO8e6NyQJfPmyjSc+Kd6qVogwk1co/5fQWubb1yXtteJcKP4GTj7gKYYNnjD3Wh1WIrlxqAzHow6e3syBrkm1VS0jc/6TNU2rB/j0IJ8wJg/mjZWKVxJrtTkLmJTuDKh7WsAyFfhVNO+RIt3x8rOm80tATguIWQue5mOayfWJ9Asq4K6XoCGuegjHdGhFmkB6X8Ld17HBYt2+2sCklRgnlWSozxIrYvdBZy5awb3PIUBl+d4DFy7gEb+doLJrySgkqDwXJpHAD1YKNMz4nXg3wobJyLVGET1UnFfTRiMbHJh69UG+LPY1gztBdXn3jBlp7kNo0q8BgsnyFmQppe+nYcaae2TvtKRFkuk+r6xsk9kcArauuJInh0Me3VJ3MSskTS2fy1FTX/AmJioPD4aBsJNgCQdnOBBQZYRckKnO13VKWqhBaU4xNqjHlGaKu2oY/Wk=
        distributions: "sdist bdist_wheel"
        skip_existing: true
